-- MySQL Script generated by MySQL Workbench
-- 12/12/20 18:41:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema jamming_stores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jamming_stores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jamming_stores` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `categoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;

USE `jamming_stores` ;

-- -----------------------------------------------------
-- Table `jamming_stores`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamming_stores`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jamming_stores`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamming_stores`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jamming_stores`.`main_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamming_stores`.`main_categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jamming_stores`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamming_stores`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `price` INT(50) NOT NULL COMMENT '',
  `final_price` INT(50) NOT NULL COMMENT '',
  `image` VARCHAR(250) NULL DEFAULT NULL COMMENT '',
  `description` VARCHAR(1000) NOT NULL COMMENT '',
  `stock` INT(11) NOT NULL COMMENT '',
  `main_category_id` INT(11) NOT NULL COMMENT '',
  `brand_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_maincategory_id_idx` (`main_category_id` ASC)  COMMENT '',
  INDEX `fk_brand_id_idx` (`brand_id` ASC)  COMMENT '',
  CONSTRAINT `fk_brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `jamming_stores`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maincategory_id`
    FOREIGN KEY (`main_category_id`)
    REFERENCES `jamming_stores`.`main_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jamming_stores`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jamming_stores`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(50) NOT NULL COMMENT '',
  `password` VARCHAR(100) NOT NULL COMMENT '',
  `category_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `file` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `fk_category_id_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `jamming_stores`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
